<a href="https://colab.research.google.com/github/JinsarAhmed/DataScience-20SW116/blob/main/20SW116_Lab_04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Lab No-04 Tasks**
#**Lab-04: Introduction to NumPy**
#**Roll-No: 20SW116 (JINSAR AHMED)**
#**Section: 2**

#TASK: 01

In [ ]:
import numpy as np
# Using the Built-in functions you learned about in the
# previous lesson, create a 4 x 4 ndarray that only
# contains consecutive even numbers from 2 to 32 (inclusive)

X = np.arange(2,33,2).reshape(4,4)
print(X)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]


#TASK: 02


In [ ]:
import numpy as np

# Create a 5 x 5 ndarray with consecutive integers from 1 to 25 (inclusive).
# Afterwards use Boolean indexing to pick out only the odd numbers in the array

# Create a 5 x 5 ndarray with consecutive integers from 1 to 25 (inclusive).
X = np.arange(1,26).reshape(5,5)
print(X)
# Use Boolean indexing to pick out only the odd numbers in the array
Y = X[X%2 != 0]
Y

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25])

#TASK: 03

In [ ]:
import numpy as np

# Use Broadcasting to create a 4 x 4 ndarray that has its first
# column full of 1s, its second column full of 2s, its third
# column full of 3s, etc..

first_col = np.ones((4, 1), dtype=int)
X = first_col * np.arange(1, 5,)

print(X)



[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]


# **THE END**